---
title: "Лабораторная работа №1"
author: Сысоев Г.А.
format:
    md:
        output-file: readme.md
    
editor: visual
---

## Цель Работы

1.  Изучить возможности технологии Yandex Query для анализа структурированных наборов данных
2.  Получить навыки построения аналитического пайплайна для анализа данных с помощью сервисов Yandex Cloud
3.  Закрепить практические навыки использования SQL для анализа данных сетевой активности в сегментированной корпоративной сети

## Ход работы

## Задание 1

### Известно, что IP адреса внутренней сети начинаются с октетов, принадлежащих интервалу \[12-14\]. Определите количество хостов внутренней сети, представленных в датасете.

<image src = "images\a.jpg">

### Ответ: 363364

## Задание 2

### Определите суммарный объем исходящего трафика

<image src = "images\b.jpg">

### Ответ: 6726396441

## Задание 3

### Определите суммарный объем входящего трафика

<image src = "images\c.jpg">

### Ответ: 12459379906

## Вывод

Изучил возможности Yandex Query и закрепил навыки использования SQL для анализа данных сетевой активности
