---
title: "Лабораторная работа №1"
author: Сысоев Г.А.
format:
    md:
        output-file: readme.md
    
editor: visual
---


## Цель Работы

1. 	Изучить возможности технологии Yandex DataLens для визуального анализа структурированных наборов данных 
2.	 Получить навыки визуализации данных для последующего анализа с помощью сервисов Yandex Cloud 
3. 	Получить навыки создания решений мониторинга/SIEM на базе облачных продуктов и открытых программных решений 
4. 	Закрепить практические навыки использования SQL для анализа данных сетевой активности в сегментированной корпоративной сети


## Ход работы

## Задание
### Используя сервис Yandex DataLens настроить доступ к результатам Yandex Query, полученным в ходе выполнения практической работы №1, и визуально представить результаты анализа данных

## Задача 1

### Представить в виде круговой диаграммы соотношение внешнего и внутреннего сетевого трафика

<image src = "images\a.jpg">

### Ответ: 363364

## Задача 2

### Представить в виде столбчатой диаграммы соотношение входящего и исходящего трафика из внутреннего сетвого сегмента.

<image src = "images\b.jpg">

### Ответ: 6726396441

## Задача 3

### Построить график активности (линейная диаграмма) объема трафика во времени.

<image src = "images\c.jpg">

### Ответ: 12459379906

## Задача 4

### Все построенные графики вывести в виде единого дашборда в Yandex DataLens.

<image src = "images\d.jpg">


## Вывод

Изучил возможности Yandex DataQuery и закрепил навыки вищуализации сетевой активнойсти чартами и построения дашбордов.